### ISSUE TITLE
Saving an MLP not possible, no attribute 'save'

### ISSUE THREAD

**Issue by skjerns** [jonnor/emlearn#4]
When trying to save an MLP I receive the following error:

```python
import numpy as np
import emlearn
from sklearn.neural_network import MLPClassifier

X = np.random.random([50,50])
y = np.random.randint(0,4, 50)
mlp = MLPClassifier([10,10])
mlp.fit(X,y) 

cmodel = emlearn.convert(mlp)
cmodel.save(file='c:/mlp.h')
```

`AttributeError: 'eml_net.Classifier' object has no attribute 'save'`

Do you know anything about this? Or is there documentation on MLP conversion that I'm missing?

(running on Windows 10, python 3.7, sklearn 0.19.2 :))

**Comment by jonnor** [comment]
Hi @skjerns thanks for reporting! Your example is exactly how it should work, but I had not implement saving the generating the C setup code yet. Working on it in PR #5
