### ISSUE TITLE
Output DecisionTreeClassifier?

### ISSUE THREAD

**Issue by skjerns** [jonnor/emlearn#6]
Is there any way to just output a DecisionTreeClassifier?

As `RandomForest` builds upon `DecisionTreeClassifier`, most of the functionality should already be implemented, right?

**Comment by jonnor** [comment]
Not supported right now, but not a lot of work to add. We can treat a DecisionTree as a Forest with a single tree, so this should be doable by a few additions to trees.py (and some tests).

**Comment by jonnor** [comment]
Fixed in `emlearn 0.6.0`, on PyPI now

**Comment by skjerns** [comment]
You're awesome!
